### ISSUE TITLE
qca-ssdk compile false

### ISSUE THREAD

**Issue by jliveusa** [robimarko/nss-packages#15]
kernel：5.10.115
repo：https://github.com/coolsnowwolf/lede
the log：
ccache_cc -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3=qca-ssdk-2022-04-07-62955de3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/openwrt/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/usr/include -I/home/openwrt/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/include/fortify -I/home/openwrt/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/include   -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/common -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/api -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/fal -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/ref -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/adpt -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/hsl -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/hsl/phy -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/sal/os -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/sal/os/linux -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/sal/sd -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/sal/sd/linux/hydra_howl -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/sal/sd/linux/uk_interface -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/init -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/hsl/hppe -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/adpt/hppe -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/include/shell_lib -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115 -I/home/openwrt/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.2.0_musl/bin/../lib/gcc//110200/include/ -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source/arch/arm64/mach-msm/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/arch/arm64/mach-msm/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source/arch/arm64/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/arch/arm64/include -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source/arch/arm64/include/asm -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/arch/arm64/include/generated -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/include/generated/uapi -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/include/uapi -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/arch/arm64/include/uapi -I/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/source/arch/arm64/include/asm/mach -include /home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.115/include/linux/kconfig.h  -DIN_ACL -DIN_FDB -DIN_IGMP -DIN_LEAKY -DIN_LED -DIN_MIB -DIN_MIRROR -DIN_MISC -DIN_PORTCONTROL -DIN_PORTVLAN -DIN_QOS -DIN_RATE -DIN_STP -DIN_VLAN -DIN_COSMAP -DIN_IP -DIN_NAT -DIN_FLOW -DIN_TRUNK -DIN_SEC -DIN_QM -DIN_INTERFACECONTROL -DIN_CTRLPKT -DIN_SERVCODE -DIN_RSS_HASH -DIN_MALIBU_PHY -DIN_AQUANTIA_PHY -DIN_QCA803X_PHY -DIN_QCA808X_PHY -DIN_SFP_PHY -DIN_PHY_I2C_MODE -DIN_VSI -DIN_PPPOE -DIN_BM -DIN_SHAPER -DIN_POLICER -DIN_UNIPHY -DUK_IF -DUK_NL_PROT= -DUK_MINOR_DEV=254 -DIN_NETLINK  -Wall -DVERSION=\"3.0.0.2\" -DBUILD_DATE=\"2022-05-21-13:25:03\" -DOS=\"linux\" -D"KBUILD_STR(s)=#s" -D"KBUILD_MODNAME=KBUILD_STR(qca-ssdk)" -DHPPE -DKVER34 -DKVER32 -DLNX26_22 -D__KERNEL__ -DKERNEL_MODULE -DMODULE -Os -pipe -march=armv8-a -mcpu=cortex-a53+crypto -fno-caller-saves -fno-strict-aliasing -Werror -fno-common -Wno-format-security -Wno-pointer-sign -Wno-unused-but-set-variable -Wno-error=unused-result -mcmodel=large -fno-stack-protector -c adpt_hppe_portctrl.c -o /home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/build/linux/KSLIB/adpt_hppe_portctrl.o
adpt_hppe_portctrl.c:62:10: fatal error: soc/qcom/socinfo.h: No such file or directory
   62 | #include <soc/qcom/socinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-2022-04-07-62955de3/make/target.mk:13: adpt_hppe_portctrl.o] Error 1

**Comment by Ansuel** [comment]
Ask him how to fix these error.
We are not affected by this.

**Comment by zxlhhyccc** [comment]
> Ask him how to fix these error. We are not affected by this.

5.15没有问题。5.10内核需添加一个socinfo.h即可，其实这个文件在你的openwrt里的ipq807x就有。

**Comment by Ansuel** [comment]
Again 5.10 is not supported and we dropped that from ages so we don't give support for that.
